version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"  # Apache runs on port 80 inside the container
    depends_on:
      - db
    env_file:
      - .env.docker
    command: |
      sh -c "php artisan config:cache &&
             php artisan migrate --force &&
             apache2-foreground"

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"  # host:container
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
